# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Hav4i' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Hav4i
  pod 'Fabric'
  pod 'Digits'
  pod 'TwitterCore'
  pod 'QuickBlox'
  pod 'JSONModel'
  pod 'SDWebImage'
  pod 'TOCropViewController'
  pod 'KVNProgress'
  pod 'AFNetworking', '~> 3.0'




end
